title: "Chia-Yi (Charlie) Chin"
description: "B.S. in Electrical Engineering @ NTU"
url: https://charliechin424.github.io
baseurl: ""

author:
  location: "Taipei, Taiwan"
  employer: "National Taiwan University"
  email: "cychin424@gmail.com"
  github: "charliechin424"
  linkedin: "https://www.linkedin.com/in/chia-yi-chin-933147247/"
